### ISSUE TITLE
Article images

### ISSUE THREAD

**Issue by ghost** [csourcesc/posts#1]
Are we supposed to say that the template is in `images/example.png` ? Maybe you should move the `images` folder in this repo.
_J'écris en anglais comme ça si ça intéresse des gens..._

**Comment by moeenio** [comment]
Sorry, what template?

**Comment by ghost** [comment]
Like this one 
![15860684540617387979591540977473](https://user-images.githubusercontent.com/45879791/78468424-51971e00-7718-11ea-9c18-cf36c8595993.jpg)

**Comment by moeenio** [comment]
Oh, you mean the image? Well yeah, the images folder is still in the main site. I could move it to here, but I'm not sure Jekyll would serve it this way, since _posts is a collection, and I'm not sure you can put folders into collections. Will look for this tho. For now, fork and do a PR in the main repository to add it to the images folder.
